
name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Hostpoint FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HP_SFTP_HOST }}
          username: ${{ secrets.HP_SFTP_USER }}
          password: ${{ secrets.HP_SFTP_PASS }}
          protocol: ftp
          port: 21
          local-dir: out/
          server-dir: /www/vezivofa.myhostpoint.ch/
